import { youtubeApiKey } from '../../utils/config';

export const state = {
	errorMessages: [],
	entities: {},
	currentMedia: {},
	currentMediaSource: {
		type: 'playList',
		id: '',
	},
	currentWebScraper: null,
	playList: [],
	sources: {},
	sourcesOrdered: [],
	showWatched: {},
	sessionHistoryPos: -1,
	sessionHistory: [],
	queue: [],
	queueClickCount: 0,
	isPlaying: false,
	shuffle: false,
	repeat1: false,
	repeatAll: false,
	showSearch: false,
	filterQuery: '',
	currentTime: 0,
	skipToTime: 0,
	mute: false,
	fullscreen: false,
	youtubeApiKey,
	showImport: false,
	showExport: false,
	showMediaEdit: null,
	showJump: false,
	jumpCursor: '',
	exportURLs: [],
	pendingImportURL: null,
	migration: {
		'audius_0.03': false,
		'audius_0.03.2': false,
	},
	showLeftMenu: false,
	leftMenuTab: 'playList',
	showSettings: false,
	showMediumSettings: {
		webscraper: false,
		matrix: false,
	},
	mainRightTab: 'about',
	isMobile: false,
	website: {
		showSearch: false,
		showChat: false,
	},
	search: {
		query: '',
		results: [],
	},
	extensionAvilable: false,
	matrixEnabled: false,
	loadedModules: {},
};
